import { StyleSheet } from 'react-native';

export const postCardStyles = StyleSheet.create({
  topNavUtility: {
    width: 40,
    height: 40,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
  },
  linkedModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  feedPostCard: {
    borderWidth: 1,
    borderRadius: 12,
    padding: 12,
  },
  feedHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
  },
  feedHeaderMeta: {
    flex: 1,
  },
  feedAvatar: {
    width: 38,
    height: 38,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  feedAvatarImage: {
    width: '100%',
    height: '100%',
  },
  feedAvatarLetter: {
    color: '#fff',
    fontWeight: '700',
    fontSize: 16,
  },
  followButton: {
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  followButtonText: {
    fontSize: 12,
    fontWeight: '700',
  },
  reportButton: {
    borderWidth: 1,
    borderRadius: 999,
    width: 36,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
  },
  postActionMenuWrap: {
    position: 'relative',
    zIndex: 1400,
    elevation: 1400,
  },
  postActionMenuCard: {
    position: 'absolute',
    top: 36,
    right: 0,
    width: 240,
    minWidth: 240,
    borderWidth: 1,
    borderRadius: 14,
    padding: 10,
    zIndex: 1500,
    shadowColor: '#000',
    shadowOpacity: 0.14,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 1500,
    overflow: 'visible',
  },
  postActionMenuTiles: {
    width: '100%',
    alignItems: 'stretch',
    gap: 10,
  },
  postActionMenuItem: {
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    minHeight: 48,
    width: '100%',
    alignSelf: 'stretch',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  postActionMenuItemText: {
    fontSize: 14,
    fontWeight: '700',
  },
  feedPostHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 8,
    marginBottom: 6,
    position: 'relative',
    zIndex: 1600,
    overflow: 'visible',
  },
  feedHeaderActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  feedCommunityHeaderLink: {
    fontSize: 13,
    fontWeight: '700',
  },
  feedAuthor: {
    fontSize: 14,
    fontWeight: '700',
  },
  feedDate: {
    fontSize: 12,
  },
  feedText: {
    fontSize: 14,
    lineHeight: 20,
  },
  feedTextWrap: {
    marginBottom: 10,
  },
  longPostBlockList: {
    gap: 10,
  },
  longPostParagraph: {
    marginBottom: 4,
  },
  longPostHeading: {
    fontWeight: '800',
    letterSpacing: 0.2,
    marginTop: 2,
  },
  longPostHeadingH1: {
    fontSize: 26,
    lineHeight: 32,
    marginBottom: 4,
  },
  longPostHeadingH2: {
    fontSize: 22,
    lineHeight: 28,
    marginBottom: 3,
  },
  longPostHeadingH3: {
    fontSize: 18,
    lineHeight: 24,
    marginBottom: 2,
  },
  longPostQuoteWrap: {
    borderLeftWidth: 3,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginVertical: 2,
  },
  longPostQuoteText: {
    fontSize: 15,
    lineHeight: 22,
    fontStyle: 'italic',
  },
  longPostImageWrap: {
    marginVertical: 4,
    overflow: 'hidden',
    borderRadius: 12,
  },
  longPostImage: {
    width: '100%',
    minHeight: 220,
    maxHeight: 460,
    borderRadius: 12,
  },
  longPostEmbedChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginVertical: 2,
    maxWidth: '100%',
    alignSelf: 'flex-start',
  },
  longPostEmbedText: {
    fontSize: 13,
    fontWeight: '600',
    maxWidth: 320,
  },
  shortPostVideoEmbedWrap: {
    width: '100%',
    aspectRatio: 16 / 9,
    borderRadius: 12,
    overflow: 'hidden',
    marginVertical: 2,
  },
  shortPostLinkPreviewCard: {
    borderWidth: 1,
    borderRadius: 12,
    overflow: 'hidden',
    flexDirection: 'row',
    alignItems: 'stretch',
    minHeight: 86,
  },
  shortPostLinkPreviewImage: {
    width: 132,
    minWidth: 132,
    height: '100%',
  },
  shortPostLinkPreviewMeta: {
    flex: 1,
    minWidth: 0,
    paddingHorizontal: 10,
    paddingVertical: 9,
  },
  shortPostLinkPreviewSite: {
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    marginBottom: 3,
  },
  shortPostLinkPreviewTitle: {
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 18,
    marginBottom: 5,
  },
  shortPostLinkPreviewDescription: {
    fontSize: 12,
    lineHeight: 16,
    marginBottom: 4,
  },
  shortPostLinkPreviewUrl: {
    fontSize: 12,
    fontWeight: '600',
  },
  postInlineEditInput: {
    borderWidth: 1,
    borderRadius: 10,
    minHeight: 280,
    paddingHorizontal: 10,
    paddingVertical: 8,
    textAlignVertical: 'top',
    fontSize: 14,
    lineHeight: 20,
  },
  postInlineEditActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 8,
  },
  postEditModalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.24)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 16,
  },
  postEditModalCard: {
    width: 780,
    maxWidth: '96%',
    minHeight: 420,
    maxHeight: '86%',
    borderWidth: 1,
    borderRadius: 14,
    padding: 14,
    gap: 12,
  },
  postMetaRow: {
    marginBottom: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  postLengthBadge: {
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  postLengthBadgeText: {
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  postPinnedBadge: {
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 4,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  postPinnedBadgeText: {
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  seeMoreText: {
    fontSize: 13,
    fontWeight: '600',
    marginTop: 4,
  },
  feedMedia: {
    width: '100%',
    height: 360,
    borderRadius: 12,
    marginBottom: 10,
  },
  feedMediaGrid: {
    width: '100%',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginBottom: 10,
  },
  feedMediaGridItem: {
    width: '49.1%',
    aspectRatio: 1,
    borderRadius: 12,
    overflow: 'hidden',
    position: 'relative',
  },
  feedMediaGridImage: {
    width: '100%',
    height: '100%',
  },
  feedMediaGridMoreOverlay: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0,0,0,0.42)',
  },
  feedMediaGridMoreText: {
    color: '#fff',
    fontSize: 24,
    fontWeight: '700',
  },
  feedStatsRow: {
    marginTop: 2,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    paddingVertical: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  reactionSummaryWrap: {
    marginTop: 8,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  reactionSummaryChip: {
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 5,
    minHeight: 32,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  reactionSummaryEmojiImage: {
    width: 14,
    height: 14,
  },
  reactionSummaryCount: {
    fontSize: 12,
    fontWeight: '700',
  },
  feedStatText: {
    fontSize: 12,
  },
  feedActionsRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 10,
  },
  feedActionButton: {
    flex: 1,
    borderWidth: 1,
    borderRadius: 10,
    paddingVertical: 9,
    paddingHorizontal: 8,
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  feedActionText: {
    fontSize: 13,
    fontWeight: '600',
  },
  commentsBox: {
    marginTop: 10,
    borderTopWidth: 1,
    paddingTop: 10,
    gap: 8,
  },
  commentThreadItem: {
    gap: 6,
  },
  detailCommentRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
  },
  detailCommentAvatar: {
    width: 34,
    height: 34,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    marginTop: 2,
  },
  detailCommentAvatarImage: {
    width: '100%',
    height: '100%',
  },
  detailCommentAvatarLetter: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '700',
  },
  detailCommentBubble: {
    flex: 1,
    borderWidth: 1,
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 9,
    gap: 2,
  },
  detailCommentAuthor: {
    fontSize: 13,
    fontWeight: '800',
  },
  commentAuthorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  commentTimeInline: {
    fontSize: 11,
    fontWeight: '600',
    flexShrink: 0,
  },
  detailCommentText: {
    fontSize: 14,
    lineHeight: 20,
  },
  detailCommentMetaRow: {
    marginLeft: 42,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  detailCommentMetaAction: {
    fontSize: 12,
    fontWeight: '700',
  },
  commentReactionActionWrap: {
    position: 'relative',
    zIndex: 20,
  },
  commentReactionPickerPopover: {
    position: 'absolute',
    bottom: 22,
    left: -6,
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 8,
    minWidth: 260,
    maxWidth: 340,
    maxHeight: 280,
    shadowColor: '#000',
    shadowOpacity: 0.18,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 10,
  },
  commentReactionPickerScroll: {
    maxHeight: 260,
  },
  commentReactionPickerScrollContent: {
    gap: 8,
    paddingBottom: 2,
  },
  commentReactionPickerGroup: {
    gap: 5,
  },
  commentReactionPickerGroupLabel: {
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'capitalize',
  },
  commentReactionPickerEmojiRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    alignItems: 'center',
  },
  commentReactionPickerEmojiButton: {
    width: 36,
    height: 36,
    borderRadius: 999,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  commentReactionPickerEmojiImage: {
    width: 16,
    height: 16,
  },
  commentReplyLoadingSlot: {
    width: 16,
    height: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  commentReactionBubbleRow: {
    marginTop: 6,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  commentReactionChipGroup: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 4,
  },
  commentReactionChip: {
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 7,
    paddingVertical: 3,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  commentReactionEmojiImage: {
    width: 12,
    height: 12,
  },
  commentReactionCount: {
    fontSize: 11,
    fontWeight: '700',
  },
  commentReactionTotal: {
    fontSize: 11,
    fontWeight: '600',
  },
  commentRepliesWrap: {
    marginLeft: 42,
    gap: 8,
    paddingTop: 2,
  },
  commentReplyRow: {
    flexDirection: 'column',
    alignItems: 'stretch',
    gap: 4,
  },
  commentReplyMainRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
  },
  commentReplyAvatar: {
    width: 26,
    height: 26,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    marginTop: 2,
  },
  commentReplyBubble: {
    flex: 1,
    borderWidth: 1,
    borderRadius: 14,
    paddingHorizontal: 10,
    paddingVertical: 8,
    gap: 2,
  },
  commentReplyComposer: {
    flexDirection: 'column',
    gap: 6,
  },
  commentReplyInput: {
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 8,
    fontSize: 12,
  },
  commentReplySendButton: {
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 4,
  },
  commentComposer: {
    flexDirection: 'column',
    gap: 6,
  },
  commentInput: {
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 9,
    fontSize: 16,
  },
  commentSendButton: {
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  commentSendText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '700',
  },
  linkedTitle: {
    fontSize: 18,
    fontWeight: '700',
  },
  searchAvatar: {
    width: 34,
    height: 34,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  searchAvatarImage: {
    width: '100%',
    height: '100%',
  },
  searchAvatarLetter: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '800',
  },
  searchResultMeta: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  searchResultPrimary: {
    fontSize: 15,
    fontWeight: '700',
  },
  reactionListContent: {
    flex: 1,
    minHeight: 120,
  },
  reactionListScroll: {
    flex: 1,
  },
  reactionListScrollContent: {
    paddingBottom: 8,
    gap: 8,
  },
  reactionUserRow: {
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  postDetailRoot: {
    flex: 1,
    flexDirection: 'row',
  },
  postDetailTextOnlyRoot: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 18,
  },
  postDetailTextOnlyCard: {
    width: '100%',
    maxWidth: 980,
    height: '92%',
    borderWidth: 1,
    borderRadius: 16,
    overflow: 'hidden',
  },
  postDetailTextOnlyHeader: {
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderBottomWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  postDetailTextOnlyComposerWrap: {
    borderTopWidth: 1,
    padding: 12,
  },
  postDetailLeft: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
    position: 'relative',
  },
  postDetailClose: {
    position: 'absolute',
    top: 18,
    left: 18,
    width: 44,
    height: 44,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 5,
  },
  postDetailMediaWrap: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  postDetailMedia: {
    width: '100%',
    height: '100%',
    maxWidth: 980,
    maxHeight: 900,
  },
  postDetailMediaNavButton: {
    position: 'absolute',
    top: '50%',
    marginTop: -22,
    width: 44,
    height: 44,
    borderRadius: 999,
    backgroundColor: 'rgba(15, 23, 42, 0.62)',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 4,
  },
  postDetailMediaNavButtonLeft: {
    left: 16,
  },
  postDetailMediaNavButtonRight: {
    right: 16,
  },
  postDetailMediaCounter: {
    position: 'absolute',
    top: 20,
    right: 20,
    backgroundColor: 'rgba(15, 23, 42, 0.7)',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
    zIndex: 4,
  },
  postDetailMediaCounterText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '700',
  },
  postDetailMediaThumbStrip: {
    position: 'absolute',
    left: 20,
    right: 20,
    bottom: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    zIndex: 4,
    paddingRight: 20,
  },
  postDetailMediaThumbButton: {
    width: 56,
    height: 56,
    borderRadius: 10,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: 'transparent',
    backgroundColor: 'rgba(15, 23, 42, 0.45)',
  },
  postDetailMediaThumbButtonActive: {
    borderColor: '#3B82F6',
  },
  postDetailMediaThumbImage: {
    width: '100%',
    height: '100%',
  },
  postDetailMediaFallback: {
    width: '100%',
    maxWidth: 760,
    minHeight: 300,
    borderWidth: 1,
    borderColor: '#334155',
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#111827',
  },
  postDetailMediaFallbackText: {
    color: '#CBD5E1',
    fontSize: 14,
    fontWeight: '600',
  },
  postDetailRight: {
    width: 420,
    maxWidth: '42%',
    borderLeftWidth: 1,
  },
  postDetailHeader: {
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderBottomWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  postDetailBody: {
    flex: 1,
  },
  postDetailBodyContent: {
    padding: 14,
    gap: 12,
  },
  postDetailText: {
    fontSize: 15,
    lineHeight: 22,
  },
  feedEmptyText: {
    fontSize: 14,
    marginVertical: 10,
  },
  longPostCaption: {
    fontSize: 12,
    lineHeight: 18,
    marginTop: 6,
    paddingHorizontal: 2,
  },
  detailPanelTabsRow: {
    marginTop: 10,
    paddingTop: 8,
    paddingBottom: 4,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    gap: 6,
  },
  detailPanelTabButton: {
    minHeight: 32,
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    alignItems: 'center',
    justifyContent: 'center',
  },
  detailPanelTabText: {
    fontSize: 12,
    fontWeight: '700',
  },
  detailCommentItem: {
    gap: 6,
  },
  postReactionActionWrap: {
    position: 'relative',
    zIndex: 30,
    flex: 1,
  },
  postReactionPickerPopover: {
    position: 'absolute',
    bottom: 46,
    left: 0,
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 8,
    minWidth: 260,
    maxWidth: 360,
    maxHeight: 300,
    shadowColor: '#000',
    shadowOpacity: 0.18,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 10,
  },
});
