// Reads the single-file Vite build output and emits a TS module that
// exports the HTML as a string the React Native app can hand to
// react-native-webview's `source.html` prop.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const distHtml = path.resolve(here, '..', 'dist', 'index.html');
const outFile = path.resolve(here, '..', '..', 'src', 'components', 'longPostEditorHtml.ts');

if (!fs.existsSync(distHtml)) {
  console.error(`[inline] missing build output at ${distHtml}`);
  process.exit(1);
}

const html = fs.readFileSync(distHtml, 'utf8');
// Escape backticks + dollar signs so the string survives a template literal.
const escaped = html.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');

const banner = `/**
 * AUTO-GENERATED by long-post-editor-web/scripts/inline.mjs.
 *
 * Do NOT edit this file by hand. To change the editor, edit the source in
 * long-post-editor-web/ and run \`npm run build\` from there.
 */

`;
const body = `export const longPostEditorHtml: string = \`${escaped}\`;\n`;

fs.mkdirSync(path.dirname(outFile), { recursive: true });
fs.writeFileSync(outFile, banner + body, 'utf8');
console.log(`[inline] wrote ${outFile} (${(html.length / 1024).toFixed(1)} kB)`);
